# settings.toml
# プロジェクト名：bot_app

# database/ はgitしない（運用用）
# develop/ はgitする（試験用）

[env]
# 利用する環境を選択: "Develop" / "Home" / "Server / "Prec""
# location = "Home"

[mounts]
Home    = "/Volumes/Extreme SSD"
Prec    = "/Volumes/Extreme SSD"
Server = "/srv/ssd"

# ===== 環境ごとのルート定義 =====

# Develop（開発環境）: プロジェクト内を利用
[locations.Develop]
pdf_root    = "project:develop/pdf"
backup_root = "project:develop/backup"
data_root   = "project:develop/data"

# Home（Mac 運用環境（自宅））: 外付けSSDを利用
[locations.Home]
pdf_root    = "mount:Home/report/pdf"
backup_root = "project:database/backup"
backup_root2 = "mount:Home/backup"
data_root   = "project:database/data"

# Prec（Mac 運用環境（Prec））: 外付けSSDを利用
[locations.Prec]
pdf_root    = "mount:Prec/report/pdf"
backup_root = "project:database/backup"
backup_root2 = "mount:Prec/backup"
data_root   = "project:database/data"

# Server（サーバー環境）
[locations.Server]
pdf_root    = "mount:Server/pdf"
backup_root = "mount:Server/backup"
data_root   = "mount:Server/data"

# ===== 共通アプリ設定 =====
[app]
available_presets = ["Develop", "Home", "Prec", "Server"]
# bot_bucket        = "bot_data"
